### ISSUE TITLE
I cant use xlabsampler...

### ISSUE THREAD

**Issue by scaruslooner** [XLabs-AI/x-flux-comfyui#60] opened 2024-08-21 02:07 UTC
I keep getting stuck at the xlabsampler
![image](https://github.com/user-attachments/assets/39f25eeb-729a-418a-961a-f78444bfe0b8)

Sampling:   0%|                                                                                                                   | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! 'DoubleStreamBlock' object has no attribute 'processor'
Traceback (most recent call last):
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 367, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 275, in denoise_controlnet
    pred = model_forward(
           ^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 42, in model_forward
    if isinstance(block.processor, DoubleStreamMixerProcessor):
                  ^^^^^^^^^^^^^^^
  File "Z:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DoubleStreamBlock' object has no attribute 'processor'

Prompt executed in 47.95 seconds

**Comment by Falkonar** [comment] 2024-08-21 02:11
The same on different version pytorch 2.3 and 2.1 the same.

**Comment by r6danl99** [comment] 2024-08-21 02:40
I'm having the same issue

**Comment by wearock** [comment] 2024-08-21 05:24
Same issue here

**Comment by dinusha94** [comment] 2024-08-21 05:33
getting the same error after updating

**Comment by lzyor** [comment] 2024-08-21 06:34
Same issue

but it seems to work after modifying line 42 of file `ComfyUI/custom_nodes/x-flux-comfyui/sampling.py` like this.

```python
if isinstance(block.processor, DoubleStreamMixerProcessor):
    if neg_mode:
        for ip in block.processor.ip_adapters:
...
```
to

```python
if hasattr(block, 'processor') and isinstance(block.processor, DoubleStreamMixerProcessor):
    if neg_mode:
        for ip in block.processor.ip_adapters:
...
```

just applied a temporary patch and I'm not sure what the issue is.

**Comment by chaorenai** [comment] 2024-08-21 06:41
同样的问题，是什么原因呢？

**Comment by 3dgopnik** [comment] 2024-08-21 06:50
такая же проблема

**Comment by Vovanm88** [comment] 2024-08-21 08:12
> Same issue
> 
> but it seems to work after modifying line 42 of file `ComfyUI/custom_nodes/x-flux-comfyui/sampling.py` like this.
> 
> ```python
> if isinstance(block.processor, DoubleStreamMixerProcessor):
>     if neg_mode:
>         for ip in block.processor.ip_adapters:
> ...
> ```
> 
> to
> 
> ```python
> if hasattr(block, 'processor') and isinstance(block.processor, DoubleStreamMixerProcessor):
>     if neg_mode:
>         for ip in block.processor.ip_adapters:
> ...
> ```
> 
> just applied a temporary patch and I'm not sure what the issue is.

You did everything right, now fixed

**Comment by Vovanm88** [comment] 2024-08-21 14:35
Update please

**Closed by Vovanm88** 2024-08-21 14:35 UTC
